workflows:
  contador-android:
    name: Contador Android
    max_build_duration: 60

    scripts:
      - name: Configurar Android SDK
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/contador-android/local.properties"

      - name: Compilar APK Debug
        script: |
          cd "$CM_BUILD_DIR/contador-android"
          gradle assembleDebug

    artifacts:
      - contador-android/build/outputs/apk/debug/*.apk
